repos:
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args:
          - --config=.code_quality/.flake8
  - repo: https://github.com/pycqa/pylint
    rev: v2.14.5
    hooks:
      - id: pylint
        args:
          - --rcfile=.code_quality/.pylintrc
  - repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
      - id: black
        language_version: python3
        args:
          - --config
          - .code_quality/pyproject_black.toml
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args:
          - --settings-path
          - .code_quality/setup.cfg
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args:
          [
            -s,
            "B101,B301,B403,B404,B602",
            -c,
            .code_quality/bandit.yaml,
            --exclude,
            docs,
          ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.971"
    hooks:
      - id: mypy
        args:
          - --install-types
          - --non-interactive
          - --config-file=.code_quality/mypy.ini
